name: lifenest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil:
  google_fonts:
  get:
  flutter_typeahead:
# School logo upload এর জন্য
  image_picker: ^1.2.3
  easy_stepper: ^1.0.1
  country_picker_pro: ^0.0.5
  flutter_lints: ^6.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  http:
  flutter_secure_storage:
  logger: ^2.7.0
  pinput:
  audioplayers:
  firebase_core:
  firebase_auth:
  google_sign_in:
  fluttertoast: ^8.2.12
  animated_text_effects: ^0.0.7
  scribble:

dev_dependencies:
  flutter_test:
    sdk: flutter

    #statement



  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/arrow/logo2.png"
  adaptive_icon_background: "#A10A7A"
  adaptive_icon_foreground: "assets/image/arrow/logo2.png"


flutter:

  uses-material-design: true

  assets:
    - assets/image/background/background_image.png
    - assets/image/onbording/
    - assets/image/onbording/one_screen.png
    - assets/image/onbording/one_screen (2).png
    - assets/image/onbording/reboto.png
    - assets/image/auth/juno_86.png
    - assets/image/auth/
    - assets/image/arrow/
    - assets/image/arrow/arrow.png
    - assets/image/arrow/angry.png
    - assets/image/home/
    - assets/image/home/profile.png
    - assets/image/home/daily.png
    - assets/image/feature/feature_01.png
    - assets/image/feature/
    - assets/image/sos/
    - assets/image/mindtools/
    - assets/image/grounding/


