// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKOeXarXQDNP4lznELC9h7IJUnVN6JSug',
    appId: '1:724696132773:web:3d2a86fe409fc431b5714c',
    messagingSenderId: '724696132773',
    projectId: 'lifenest-659b2',
    authDomain: 'lifenest-659b2.firebaseapp.com',
    storageBucket: 'lifenest-659b2.firebasestorage.app',
    measurementId: 'G-KW8VKEE1T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mW6uBJ1kkyztATaE1Ak2g-fnVlcrwRg',
    appId: '1:724696132773:android:2f67d16a16f967cab5714c',
    messagingSenderId: '724696132773',
    projectId: 'lifenest-659b2',
    storageBucket: 'lifenest-659b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIr8XaZ4tZD_cYMlUep6Kkwe3BcgKxeV4',
    appId: '1:724696132773:ios:a51baabdaf021fa2b5714c',
    messagingSenderId: '724696132773',
    projectId: 'lifenest-659b2',
    storageBucket: 'lifenest-659b2.firebasestorage.app',
    iosClientId: '724696132773-9c0hfpcm5j1vm7som5ip0alpu2r6lcr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifenest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIr8XaZ4tZD_cYMlUep6Kkwe3BcgKxeV4',
    appId: '1:724696132773:ios:a51baabdaf021fa2b5714c',
    messagingSenderId: '724696132773',
    projectId: 'lifenest-659b2',
    storageBucket: 'lifenest-659b2.firebasestorage.app',
    iosClientId: '724696132773-9c0hfpcm5j1vm7som5ip0alpu2r6lcr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifenest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKOeXarXQDNP4lznELC9h7IJUnVN6JSug',
    appId: '1:724696132773:web:b86416ab40fc6139b5714c',
    messagingSenderId: '724696132773',
    projectId: 'lifenest-659b2',
    authDomain: 'lifenest-659b2.firebaseapp.com',
    storageBucket: 'lifenest-659b2.firebasestorage.app',
    measurementId: 'G-BV663DHV4E',
  );
}
